version: '3'

services:
  grokmirror:
    build:
      # context: ./public-inbox/
      # dockerfile: Containerfile
      context: .
      dockerfile: ./Containerfile

    # stdin_open: true
    user: "${UID}:${GID}"
    volumes:
    - ./lore.conf:/config/lore.conf:z
    - ../public-inbox/config/:/etc/public-inbox/
    - ../data/:/data:z
    command: grok-pull -v -c /config/lore.conf

